### ISSUE TITLE
R2Webview.computeHorizontalScrollRange/numPages returns larger than real width of WebView

### ISSUE THREAD

**Issue by insomnia1718** [readium/r2-testapp-kotlin#296] opened 2020-03-06 03:51 UTC
I'm using R2EPubActivity, somehow (R2Webview.computeHorizontalScrollRange / numPages) returns 1441 pixels, width of R2Webview and my phone are both 1440 pixels, it cause an offset on screen, when pageNum gets bigger, offset get bigger too. this only happend with one of my epub file, the others works well.
    
    
     val width = this.computeHorizontalScrollRange() / numPages
     val destX = (width * item)
        if (smoothScroll) {
            smoothScrollTo(destX, 0, velocity)
        } else {
            completeScroll(false)
            scrollTo(destX, 0)
            pageScrolled(destX)
        }

**Comment by mickael-menu** [comment] 2020-03-06 07:55
@insomnia1718 Thanks for reporting this, would you be able to share the problematic epub with us?

**Comment by insomnia1718** [comment] 2020-03-06 10:11
> @insomnia1718 Thanks for reporting this, would you be able to share the problematic epub with us?

Sure.
https://drive.google.com/file/d/1X-EsQ_92pZMuiLwiWqZ1Rs2Yd866Dk12/view?usp=sharing

**Comment by mickael-menu** [comment] 2020-11-12 12:48
@insomnia1718 Would you mind checking if the issue is addressed by this PR? https://github.com/readium/r2-navigator-kotlin/pull/178 Thanks

**Closed** 2020-12-08 13:39 UTC
Labels: bug
