### ISSUE TITLE
Unable to render pages when on bad internet connection

### ISSUE THREAD

**Issue by YorickPieters** [readium/r2-testapp-kotlin#43] opened 2018-07-02 11:29 UTC
When browsing an eBook and my mobile data connection is not good anymore, the app does not render the html. We get an ERR_CONNECTION_TIMED_OUT error message.

![screenshot_20180628-131943](https://user-images.githubusercontent.com/8820368/42161583-c8393920-7dfb-11e8-8075-f0588b5505df.jpg)

**Comment by YorickPieters** [comment] 2018-07-02 11:43
Occurs on: Play Store version (seen on both beta 1 and beta 2)
App version: 1.0.1
Github tag: v1.0.0-beta.2

Steps to reproduce:
- Place device in flight mode
- Open R2 Reader
- Click on a publication 
- You get an error "Webpage not available" with error code ERR_PROXY_CONNECTION_FAILED

or

- Go to a place with bad mobile data connection
- Open R2 Reader
- Click on a publication 
- You get an error "Webpage not available" with error code ERR_CONNECTION_TIMED_OUT

**Comment by HadrienGardeur** [comment] 2018-07-02 14:11
I can't reproduce this issue on my Pixel 2XL running Android 9.

**Comment by YorickPieters** [comment] 2018-07-02 14:48
I'll try and gather more info on when it occurs. It does not always seem to trigger, just now I was able to work in flightmode again. It seems to occur mostly on one of my 2 mobile data connections, I even got a DNS lookup failed error at some point.

**Comment by llemeurfr** [comment] 2018-07-02 16:48
Yes, as this is not visible on my android tablet when I put it in flight mode.

**Comment by YorickPieters** [comment] 2018-07-04 09:18
Additional information. The cause of this issue seems to be that one of my Mobile Data (base gprs) providers had a proxy active. If I disable the proxy server for that provider the app works fine.
It is weird that Android would allow a localhost call to be passed on to that proxy.
One of my colleagues found a similar report on this project: https://github.com/syncthing/syncthing-android/issues/440

**Comment by llemeurfr** [comment] 2018-07-04 09:34
Reading the syncthing thread, seems there is no solution that doesn't involve a modification of the device config by the user. If true, that would be a mess.

**Comment by HadrienGardeur** [comment] 2020-02-05 10:13
We need to investigate ASAP if this is still an issue.

**Comment by mickael-menu** [comment] 2021-01-18 17:18
I'm closing because I can't reproduce and I don't think we got any more similar report since then. R2 has been used in production for a while now.

This other issue that we'll tackle soonish should render this moot anyway: https://github.com/readium/r2-testapp-kotlin/issues/297

**Closed by mickael-menu** 2021-01-18 17:18 UTC
Labels: bug
