### ISSUE TITLE
EPUB reader not works correctly on Android < 7.0

### ISSUE THREAD

**Issue by m-ochyra** [readium/r2-testapp-kotlin#405] opened 2021-04-19 10:08 UTC
Hi, I found some problem in switching pages in EPUB on Android devices with Android version lower than 7.0.

Is there implemented something like forced scroll mode? I founded this issue on both branches: master and develop.

Something is wrong also in changing view settings: nothing works.

Please see my videos:

https://user-images.githubusercontent.com/5583015/115219174-8a2d4e00-a107-11eb-916b-cf20f7e6f9bb.mov
https://user-images.githubusercontent.com/5583015/115219333-ba74ec80-a107-11eb-8bb8-2da998c86706.mov

**Comment by mickael-menu** [comment] 2021-04-19 10:27
It looks like the JavaScript is broken and seems like a duplicate of https://github.com/readium/r2-navigator-kotlin/issues/127 to me.

Maybe take a look if [installing the Chromium web view](https://github.com/readium/r2-navigator-kotlin/issues/127#issuecomment-763816976) helps you there.

**Closed by mickael-menu** 2021-04-19 10:27 UTC
