### ISSUE TITLE
Display issue with EPUB FXL

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-kotlin#445] opened 2021-07-20 08:53 UTC
## Bug Report

Reported by an EPUB author, Amkiram Moors. Appears at least on the Android version of the Bläddra app from kb.se and the Biblio app from Axiell Media. 

### What happened?

On the right-hand side of the page, the margin would often be ignored, making the text run right up to the right edge of the screen. It did not cut of distort the illustration at all, so it clearly shifted the text-box on display. I got the feeling this had to do with margins and the width of the div container, but this was happening to another person working on different books as well, and this wasn't happening in any other app or programme, so it made me wonder. 
Another problem is that it ignores the "auto" display in the book, and does not display in landscape mode at all: if you turn your phone on the side, it zooms into the single page you are on, and stays zoomed.

To solve this we'll need:
- a sample of a faulty FXL publication
- more details from kb.se and Axiell Media developers.

**Comment by Jokez80** [comment] 2021-08-16 05:58
KB.se answer:

I cant tell you more than that we have had reports from our authors and publishers that when they create a epub file it seems like the reader in our app don´t handle their margins as they expected.

I believe we are not doing anything when we starting a reader to make it not handle margins as it should.

**Comment by Jokez80** [comment] 2021-09-13 09:32
Here are three examples from the app Bläddra: We mostly have a problem that on Android the size of the text gets to big and overflows. 


![exempel1](https://user-images.githubusercontent.com/685818/133060172-d98bd5c7-2382-4012-a547-54b584eb466b.jpg)
![exempel3](https://user-images.githubusercontent.com/685818/133060176-005b97ce-4a93-424b-8524-4786b0346c6b.jpg)
![exempel2](https://user-images.githubusercontent.com/685818/133060179-b3012337-1311-46e3-ba3b-58c718f21cb6.jpg)

**Comment by mickael-menu** [comment] 2022-07-29 14:11
Duplicate of https://github.com/readium/readium-css/issues/115, I think.

**Closed by mickael-menu** 2022-07-29 14:11 UTC
