### ISSUE TITLE
Table Of Content UTF8 Issue

### ISSUE THREAD

**Issue by voipworld** [readium/r2-testapp-kotlin#258] opened 2019-11-22 21:41 UTC
hello,
i love your project and its pretty powerfull for blind users using android to read eBooks
my prefaired format is ePub, and my prefaired library ofer only this format..., and i compiled this project myself to see if its accessible, maybe i can ofer some testing? ;)
so, the issue is with UTF8, if i am not wrong..., because if i open a arabic book, and chouse the table of content, i get this Exception:
11-22 22:27:58.706 29171 29171 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { (has extras) }} to activity {org.readium.r2reader/org.readium.r2.testapp.epub.EpubActivity}: org.json.JSONException: End of input at character 4 of #C11                                                
11-22 22:27:58.706 29171 29171 E AndroidRuntime: Caused by: org.json.JSONException: End of input at character 4 of #C11
if you want to try any book, please download this one:
http://d.shamela.ws/epubs/028/2864.epub
i hope i can get it to work, i love readium!

**Comment by mickael-menu** [comment] 2021-01-18 17:23
Hi @voipworld and sorry for the delay treating your issue.

I can't reproduce on the latest version with any of my Arabic and Cyrillic books, so I'm going to close this issue. Unfortunately I can't test your book because the link expired. But if you can upload it again I can check again with it.

**Closed by mickael-menu** 2021-01-18 17:23 UTC
Labels: bug
