### ISSUE TITLE
EPUB cover too large for the database

### ISSUE THREAD

**Issue by cnelindiahwe** [readium/r2-testapp-kotlin#353] opened 2020-08-25 11:52 UTC
Normal text epub file is working but we are unable to open **audio, video multimedia** Epub file.
Epub 3 supports multimedia but it does not work for me with this code.

**Comment by mickael-menu** [comment] 2020-08-31 07:16
@cnelindiahwe Which version of Readium are you using?

Can you try with this file: https://github.com/IDPF/epub3-samples/releases/download/20170606/cc-shared-culture.epub It contains a video on some of the pages, and this is the one we use in general to test video playback.

Also, it could help if you are able to share (even privately on [Slack](http://readium-slack.herokuapp.com/)) one of the EPUBs that don't work for you.

**Comment by cnelindiahwe** [comment] 2020-08-31 13:28
We are using `v2.2.0`
We tried with given file https://github.com/IDPF/epub3-samples/releases/download/20170606/cc-shared-culture.epub it works for me but below file contain video and when i open file, app is closed.  
https://kstyles.app/wp-content/uploads/2020/08/11.epub

`` FATAL EXCEPTION: main
    Process: org.readium.r2reader, PID: 32663
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.readium.r2reader/org.readium.r2.testapp.epub.EpubActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:151)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:139)
        at org.jetbrains.anko.db.SqlParsersKt.parseList(SqlParsers.kt:79)
        at org.readium.r2.testapp.db.BOOKS$currentLocator$1$1.invoke(BooksDatabase.kt:260)
        at org.readium.r2.testapp.db.BOOKS$currentLocator$1$1.invoke(BooksDatabase.kt:200)
        at org.jetbrains.anko.db.SelectQueryBuilder.exec(SelectQueryBuilder.kt:44)
        at org.readium.r2.testapp.db.BOOKS$currentLocator$1.invoke(BooksDatabase.kt:259)
        at org.readium.r2.testapp.db.BOOKS$currentLocator$1.invoke(BooksDatabase.kt:200)
        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:177)
        at org.readium.r2.testapp.db.BOOKS.currentLocator(BooksDatabase.kt:256)
        at org.readium.r2.testapp.epub.EpubActivity.onCreate(EpubActivity.kt:238)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
``

**Comment by cnelindiahwe** [comment] 2020-08-31 14:05
Which software you are using for creating multimedia(video, audio) epub file?

**Comment by mickael-menu** [comment] 2020-08-31 15:11
Looking at your logs, I think the issue is with the size of the cover in your EPUB file.

Right now in the test app, covers are stored directly in the database, and the size is quite limited (I see that in your EPUB it is 3MB). This issue will need to be fixed in the test app, but in the meantime:

If you're developing your own reading app:
* Save the covers in a file system directory instead of the database (recommended)
* Resize the covers to limit their size

If you're authoring the EPUB file, just make sure that the cover is not too large.

> Which software you are using for creating multimedia(video, audio) epub file?

I'm not authoring any EPUB personally.

**Comment by cnelindiahwe** [comment] 2020-09-01 12:54
We create new epub file that contain only text and video but video is not playing
https://kstyles.app/wp-content/uploads/2020/09/Add-Video-375x500px-010920-2.epub

how to set the epub file for using "word spacing feature & video play"?
Audio, Video play button is not clickable on Readium

 So, I am sharing these files and how to make it clickable on readium app

https://kstyles.app/wp-content/uploads/2020/09/150820EbookTestingMultimedia.epub
https://kstyles.app/wp-content/uploads/2020/09/KstylesTV-Ebook-Sample-Ainstudio.epub

**Comment by mickael-menu** [comment] 2020-09-02 07:47
It looks like there's a bug with fixed layout EPUB in the navigator, the touch handling code is not triggered. Until we fix this, if you're able to create a reflowable EPUB (it will give you the word spacing feature as well and font resize) the video will work.

**Closed** 2020-10-08 08:01 UTC
Labels: bug
