### ISSUE TITLE
Handle device orientation (Audiobook)

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-kotlin#237] opened 2019-09-25 13:46 UTC

**Comment by llemeurfr** [comment] 2019-10-11 12:17
duplicate of #238

**Comment by llemeurfr** [comment] 2019-11-26 11:57
In fact not a duplicate.

**Comment by mickael-menu** [comment] 2021-01-13 10:31
This issue should be fixed by now.

**Closed** 2021-01-13 10:31 UTC
Labels: enhancement
