### ISSUE TITLE
Getting this crash when opening the Reader screen In Android Studio 4.2.1

### ISSUE THREAD

**Issue by ajay9889** [readium/r2-testapp-kotlin#429] opened 2021-06-04 09:32 UTC
**Getting this crash when opening the Reader screen using Android Studio 4.2.1 updated version** 

PID: 26861
    java.lang.NoSuchMethodError: No static method getSeconds(I)D in class Lkotlin/time/DurationKt; or its super classes (declaration of 'kotlin.time.DurationKt' appears in /data/app/packageName-gCEFWUbuh-UKhN4WY1pKfw==/base.apk!classes5.dex)
        at org.readium.r2.lcp.license.LicenseValidation.fetchStatus(LicenseValidation.kt:318)
        at org.readium.r2.lcp.license.LicenseValidation$handle$1.invokeSuspend(LicenseValidation.kt:274)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at org.readium.r2.lcp.license.LicenseValidation.handle(LicenseValidation.kt:270)
        at org.readium.r2.lcp.license.LicenseValidation.setState(LicenseValidation.kt:99)
        at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$13.invoke(LicenseValidation.kt:259)
        at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$13.invoke(LicenseValidation.kt:84)
        at org.readium.r2.lcp.license.StateMachine.notifyOnTransition(StateMachine.kt:75)
        at org.readium.r2.lcp.license.StateMachine.transition(StateMachine.kt:32)
        at org.readium.r2.lcp.license.LicenseValidation.raise(LicenseValidation.kt:265)
        at org.readium.r2.lcp.license.LicenseValidation.validateLicense(LicenseValidation.kt:312)
        at org.readium.r2.lcp.license.LicenseValidation.access$validateLicense(LicenseValidation.kt:84)
        at org.readium.r2.lcp.license.LicenseValidation$handle$1.invokeSuspend(LicenseValidation.kt:273)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at org.readium.r2.lcp.license.LicenseValidation.handle(LicenseValidation.kt:270)
        at org.readium.r2.lcp.license.LicenseValidation.setState(LicenseValidation.kt:99)
        at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$13.invoke(LicenseValidation.kt:259)
        at org.readium.r2.lcp.license.LicenseValidation$stateMachine$1$13.invoke(LicenseValidation.kt:84)
        at org.readium.r2.lcp.license.StateMachine.notifyOnTransition(StateMachine.kt:75)
        at org.readium.r2.lcp.license.StateMachine.transition(StateMachine.kt:32)
        at org.readium.r2.lcp.license.LicenseValidation.raise(LicenseValidation.kt:265)
        at org.readium.r2.lcp.license.LicenseValidation.observe(LicenseValidation.kt:292)
        at org.readium.r2.lcp.license.LicenseValidation.validate(LicenseValidation.kt:113)
        at org.readium.r2.lcp.service.LicensesService.retrieveLicense(LicensesService.kt:106)
        at org.readium.r2.lcp.service.LicensesService.access$retrieveLicense(LicensesService.kt:30)
        at org.readium.r2.lcp.service.LicensesService.retrieveLicense(LicensesService.kt:71)
        at org.readium.r2.lcp.service.LicensesService$retrieveLicense$license$1.invokeSuspend(LicensesService.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

**Comment by io7m** [comment] 2021-06-04 10:03
These sorts of errors almost always indicate a dependency conflict.

1. Which version of Kotlin is the LCP service compiled against?
2. Which version of Kotlin is your application compiled against?

Android Studio is not above warning you that the version of Kotlin used in build doesn't match the one bundled with the IDE, and will offer to update your build even if that actually ends up breaking it. :sweat:

**Comment by chrfalch** [comment] 2021-06-04 10:14
I had this the other day as well - and found a reference to 'androidx.core:core-ktx:1.2.0' in my gradle file which was conflicting with the version that `r2-lcp-kotlin` / `r2-navigator` was using ('androidx.core:core-ktx:1.3.2'). Hope this solves your issue as well.

**Comment by ajay9889** [comment] 2021-06-04 10:29
Below are the version Details:

Kotlin Version : 

ext.kotlin_version = '1.4.31'

Using below in App-level build.gradle which was working before. Now, it is not working 

implementation 'androidx.core:core-ktx:1.6.0-alpha01' [Now, we have beta one too]

---
Navigator gradle I am using this way:

 implementation "com.github.readium:r2-navigator-kotlin:2.0.0"

@chrfalch do i need to use the gradle "androidx.core:core-ktx:1.3.2" as the navigator has this version which cannot be change.

**Comment by chrfalch** [comment] 2021-06-04 10:38
I'm not sure what you need to do - Just sharing my experience :)

I have version `1.4.31` of Kotlin as well, don't think that's the problem - would check out if changing the version of `androidx.core:core-ktx` would solve your problem.

**Comment by ajay9889** [comment] 2021-06-04 10:45
@io7m , I am using the same Kotlin version  1.4.31 in App and readium module as well. But, still getting crash. I just updated Android Studio with 4.2.1 and classpath 'com.google.gms:google-services:4.3.8'

**Comment by ajay9889** [comment] 2021-06-04 10:46
@chrfalch , still crashing after downgrading the version androidx.core:core-ktx  to 1.3.2

**Comment by mickael-menu** [comment] 2021-06-04 10:47
I just upgraded to Android Studio 4.2.1 and was able to build the test app without issue. Maybe double-check your dependencies with its `build.gradle`?

> @chrfalch do i need to use the gradle "androidx.core:core-ktx:1.3.2" as the navigator has this version which cannot be change.

I think Gradle should take by default the most recent declared version, when there are conflicts. So the version in the navigator's `build.gradle` doesn't really matter. You are also able to explicitly override versions:

https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

**Comment by chrfalch** [comment] 2021-06-04 10:47
Ok, then I don't know how to solve this. Have tried removing the reference to `androidx.core:core-ktx` in your gradle file and let the gradle file in the r2-* libraries be used? That's in fact what I did - remember to clean / sync before building

**Comment by chrfalch** [comment] 2021-06-04 10:50
> I think Gradle should take by default the most recent declared version, when there are conflicts. So the version in the navigator's `build.gradle` doesn't really matter. 

That should be correct, but there seems to be an issue with these `@OptIn` attributes that someone (somewhere I don't remember) mentioned.

The test app doesn't include the `androidx.core:core-ktx` reference in its gradle file, so the app should build and compile just fine.

**Comment by mickael-menu** [comment] 2021-06-04 10:50
I'm closing this issue as it doesn't seem to be directly related to Readium, but feel free to continue here.

**Closed** 2021-06-04 10:50 UTC

**Comment by ajay9889** [comment] 2021-06-04 13:43
@mickael-menu and @chrfalch , the crash is still happening after removing "androidx.core:core-ktx" dependencies

**Comment by benforsrup** [comment] 2021-06-08 14:14
Can confirm, getting the same crash

**Comment by mickael-menu** [comment] 2021-06-08 14:22
It could help if one of you produced a minimal project showing the issue.

**Comment by chrfalch** [comment] 2021-06-09 07:21
It seems like the root cause for this issue is that the `.seconds` method in the `Duration` class needs the attribute `@Optin(ExperimentalTime)` on classes using the method. The attribute needs a specific version of `androidx.core:core-ktx` that supports this functionality. Cleaning up the gradle files making sure that there are no mismatches in versions was my solution

**Comment by stevenzeck** [comment] 2021-06-17 02:00
If you're getting this error, there is a dependency resolution problem somewhere.  Right now Readium only supports Kotlin 1.4.31.

Open your Project Structure, select Dependencies on the left, and select All Modules.  In the list of All Dependencies scroll down and look for `org.jetbrains.kotlin:kotlin-stdlib-common`.  You'll likely see a tree to expand.  Select each version and see which module(s) are using which version.  If it's something in your control, try downgrading it.  More than likely it's a coroutines library.

![image](https://user-images.githubusercontent.com/8315038/122319029-a2420380-cee5-11eb-83b3-dccb62f66783.png)

**Comment by mickael-menu** [comment] 2021-06-18 13:47
There's currently a discussion on Slack. I think we are going to move to 1.5 eventually. If you want to chime in: https://readium.slack.com/archives/C703MSTQU/p1624013768088700
